// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcs025xnNYByPH7_Jo4UtMhXEkuKR8DjM',
    appId: '1:766440816611:web:5b5d722a81f02d4d12aad6',
    messagingSenderId: '766440816611',
    projectId: 'habitshare-65ed9',
    authDomain: 'habitshare-65ed9.firebaseapp.com',
    storageBucket: 'habitshare-65ed9.firebasestorage.app',
    measurementId: 'G-SD5B12YF6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwaJiABL8up_2ZdVfT4sORzB3mwJPfvKE',
    appId: '1:766440816611:android:30d20c1f5800e61f12aad6',
    messagingSenderId: '766440816611',
    projectId: 'habitshare-65ed9',
    storageBucket: 'habitshare-65ed9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUseTy21sFRG-taw3_UHl3ocw1p2K4RvY',
    appId: '1:766440816611:ios:06e14383fe6572c612aad6',
    messagingSenderId: '766440816611',
    projectId: 'habitshare-65ed9',
    storageBucket: 'habitshare-65ed9.firebasestorage.app',
    iosBundleId: 'com.example.habitshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUseTy21sFRG-taw3_UHl3ocw1p2K4RvY',
    appId: '1:766440816611:ios:06e14383fe6572c612aad6',
    messagingSenderId: '766440816611',
    projectId: 'habitshare-65ed9',
    storageBucket: 'habitshare-65ed9.firebasestorage.app',
    iosBundleId: 'com.example.habitshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcs025xnNYByPH7_Jo4UtMhXEkuKR8DjM',
    appId: '1:766440816611:web:c0a09e0d68ed600a12aad6',
    messagingSenderId: '766440816611',
    projectId: 'habitshare-65ed9',
    authDomain: 'habitshare-65ed9.firebaseapp.com',
    storageBucket: 'habitshare-65ed9.firebasestorage.app',
    measurementId: 'G-31V55KQMVE',
  );
}
