-keep class com.google.android.gms.** { *; }
-keep class com.google.firebase.** { *; }
-keep class com.dexterous.flutterlocalnotifications.** { *; }
-dontwarn com.google.android.gms.**
-dontwarn com.google.firebase.**
